#!/bin/sh
#
# Script to perform some basic operations to the code before committing.

# Adds file hashes to html script imports for cache busting purposes
sh .devtools/updatehashes.sh

# Adds file to current commit
git add --all