#!/bin/sh
#
# Script to perform some basic operations to the code before committing.

# Adds file hashes to html script imports for cache busting purposes
powershell .devtools/updatehashes.bat gitadd

# Adds file to current commit
git add "**.html"